### PR TITLE
Make ZoneName optional

### PR DESCRIPTION
**Pull request by Mario-F**
I have many domains to manage with cert-manager but have to create an issuer for each of them, so i made the ZoneName parameter optional and implement an ZoneName search.

Also fixed an bug with cleanup not finding record if cert-manager provides it case-sensitiv.

### CODE REVIEW

**Comment by t-knapp** [comment]
Is it possible to have one ClusterIssuer that deals with multiple domains? I have two domains controlled at Hetzner DNS both used for deployments in same cluster. How can one ClusterIssuer deal with both Zones? Or do I have to create one (Cluster)Issuer for each zone?

**Comment by Mario-F** [comment]
@t-knapp yeah with the latest version just omit the zoneName and the Issuer can handle all Domains available in your Account.

**Comment by t-knapp** [comment]
For some reason the lookup does not work. Plugin says it cannot handle more than one zone in the response of HTTP /zones call.

https://github.com/vadimkim/cert-manager-webhook-hetzner/blob/master/main.go#L253

Problem is an empty `config.ZoneName` that lead to all of my zones be part of the response.

**Comment by Mario-F** [comment]
@t-knapp are you sure using the latest version? I think @vadimkim has not yet updated the docker image and helm chart in this repository.
Because i needed this feature, i have made my own chart with manual uploaded docker image: https://github.com/Mario-F/helm-charts/blob/main/charts/cert-manager-webhook-hetzner/README.md

At lest you should able to see either the Found ID logmessage or error as you can see in the code: https://github.com/vadimkim/cert-manager-webhook-hetzner/blob/450b4d8e846ed56a9bb20ac0527e8aa40b31e347/main.go#L284

**Comment by vadimkim** [comment]
sorry for the late merge. I will update package asap

**Pull request merged**
