### PR TITLE
Fix namespaces for SA and Service

### PR DESCRIPTION
**Pull request by mbeham**
ServiceAccount and Service are missing the namespace directive.

### CODE REVIEW

**Comment by ibotty** [comment]
Thank you for your contribution.  I thought that Helm sets the namespace by default.  Did you run into any problems without this patch?

The change looks reasonable. @vadimkim: Are you OK with it?

**Comment by mbeham** [comment]
Yes, you are right. `helm install` does this. But e.g. `helm template`, which creates the resulting YAML files, doesn't have this fallback option.

**Comment by dgiebert** [comment]
LGTM, would be able to test and merge this weekend.

**Comment by vadimkim** [comment]
I'll put it together with dependencies version upgrade and release on weekend

**Pull request merged**
